### ISSUE TITLE
Dependency on regex

### ISSUE THREAD

**Issue by dmit** [mrseanryan/in_definite#7]
Hi! Thank you for this crate.

Would you be interested in a PR that removes the dependency on `regex`, making this crate standalone? On my PC the resulting binary goes from 1.2MB to 0.2MB in size, and (clean) compile time from ~13s to <1s after this change.

**Comment by mrseanryan** [comment]
Hi @dmit - for sure, that sounds a good improvent.
 If you open a PR, that would be great
